### ISSUE TITLE
Links to the poll owner profile

### ISSUE THREAD

**Issue by p4u** [vocdoni/vote-frame#104]
- [x] On the user profile page (https://farcaster.vote/app#/profile/p4u) add a link to the warpcast profile
- [x] On the poll view, show the owner and add a link to the farcaster.vote profile page https://farcaster.vote/app#/poll/4ae20a8eb4caa52f5588f7bb9f3c6d6b7cf003a5b03f4589edea10000000026f)
- [x] The Leaderboard for "Latest polls" shoould also have a link to the owner profile too

**Comment by elboletaire** [comment]
Closed in 8073d335b4212e9e76d4f83d51c2a44609f30ae3
