### ISSUE TITLE
No funds when connected to another network

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/vote-frame#106]
If you have selected another network other than degenchain in your wallet, it will say that you don't have enough funds, even if you have enough

![image](https://github.com/vocdoni/vote-frame/assets/3515290/7d9396df-0a5f-4390-9531-cf5982e93db0)

To make this work, you have to select Degen in your wallet and then do a hard refresh: ctrl+shift+r

**Comment by elboletaire** [comment]
Closed in 70d290645549da1e502f810d37c6cdb431405e95 and 96f002ed5999c668f95b0ceab0e84cead9136112
