### ISSUE TITLE
Vote reminds via warpcast DMs

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/vote-frame#124]
The communities administrators must be able to send customizable direct messages to remind to some (even all) users in a census for a certain poll.

All required API changes are detailed on #121 (WIP PR)

**Comment by ferranrego** [comment]
It would be great if we can also sort the list of users by weight, so the big holders are easy to identify.


<img width="513" alt="image" src="https://github.com/vocdoni/vote-frame/assets/3515290/fe69d331-1cec-4f0d-9d68-f28504a9dfbc">

**Comment by elboletaire** [comment]
> It would be great if we can also sort the list of users by weight, so the big holders are easy to identify.

Please create a new issue for this to not block this issue for now.

**Comment by lucasmenendez** [comment]
It is already done
