### ISSUE TITLE
Featuring communities

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/vote-frame#127]
Let's highlight the most relevant communities (manually for now).

These should appear first:
- Haberdashery
- Proxyswap DAO
- NFTDegen channel
- Anthropology
- Vocdoni Friends
<img width="1160" alt="image" src="https://github.com/vocdoni/vote-frame/assets/3515290/12a416b0-f0ab-467a-b7b2-fa70adfb26ac">

**Comment by elboletaire** [comment]
So it's just a matter of changing how the backend returns the list of communities, to be sorted via featured AND creation date.
