### ISSUE TITLE
Review if it makes sense to integrate Votecaster into the Composer Actions of Warpcast

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/vote-frame#153]
Review if it makes sense to integrate Votecaster into the Composer Actions of Warpcast and assess the work it would require.

Specs: [Draft - Composer Actions](https://warpcast.notion.site/Draft-Composer-Actions-7f2b8739ee8447cc8a6b518c234b1eeb)

**Comment by elboletaire** [comment]
Yes it does

**Comment by ferranrego** [comment]
^_^
