### ISSUE TITLE
Weabpp UI fixes and feature implementation

### ISSUE THREAD

**Issue by selankon** [vocdoni/vote-frame#67]
### OLD:
- [x] Implement box for group chat
- [x] Implement notify users switch on community creation screen
- [x] Implement notify users switch on poll creation screen
- [x] Implement a loader on community creation screen
- [x] Delete censusName field
- [x] Redirect to a community is created page
- [x] Implement style on community created page  + link a degen chain (awaiting design)
- [x] Fix group chats links (awaiting design)
- [x] Community detail view (awaiting design)
- [x] Implement myCommunities component
- [x] Implement disable myCommunity on community detail page
- [x] Dropdown community based or Custom census Show only communities you administrate on poll creation
- [x] Add logo description text (community creation)
- [x] Add link on community detail pointing to the contract on degen explorer
- [x] By default, the selected option in the poll form should be Community based, not All Farcaster.
- [x] Add community avatar on poll creation form
- [x] Implement cost from contract
- [x] Add bell on the notify text on poll creation 🔔
- [x] Change navbar order

### NEW:

- [x] Notifications only for communities
- [x] Handle no funds for create community, review the payment component and include a link to the Degen bridge
- [x] Update bot copies
- [x] Small UI changes:
  - [x] Add Github in the footer (related #56)
  - [x] Show channel icon in channels (suggestions and selectors)
  - [x] Leaderboard section: Clicking on a poll should redirect to its public page on Farcaster.vote, not to the poll creator's profile.
  - [x] Remove the channel and group chat info if the user didn't add one during the community creation
![Screenshot 2024-04-24 at 11 57 20](https://github.com/vocdoni/vote-frame/assets/9265364/6fe1a7b5-8040-47a6-8fb0-ff80ee4c93b4)
  - [x] Move "View contract" to "Results verifiable" box
  - [x] Change "Live" badge to "Results settle on-chain (Check)"
  - [x] Edit order of footer links to: github farcast twitter discord
  - [x] Edit poll info subtitules to:
```
Participant Turnout
Members who voted versus total members in the census.

Voting Power Turnout
Total votes cast versus total vote weight
```
- [x] Support for enable and disable communities:
  - [x] Include enable/disable options
  - [x] Listen for contracts events.
- [ ] #100
- [ ] #101
![telegram-cloud-photo-size-4-5850666320071344127-y](https://github.com/vocdoni/vote-frame/assets/3515290/bba934e5-ae63-4729-b1fa-da2b99fc0c6b)
- [ ] #102
- [x] Timeout to refresh communities automatically 
- [x] We should unify the public polls pages with the same design. Now there are different public poll pages. This new design ([example](https://farcaster.vote/app#/communities/1/poll/4ae20a8eb4caa52f5588f7bb9f3c6d6b7cf003a5b03f4589edea100000000251)), that should be the one used everywhere, and the old design ([example](https://farcaster.vote/app#/poll/4ae20a8eb4caa52f5588f7bb9f3c6d6b7cf003a5b03f4589edea10000000024d))

**Comment by lucasmenendez** [comment]
The endpoint to disable a community is ready:

```
Method: DELETE
URI: /communities/{communityID}
Authorization: Bearer {userAuthToken}
```

cc/ @selankon You can check an example of how to make a call with the user token in the `Profile` view.

**Comment by ferranrego** [comment]
Added this todo: By default, the selected option in the poll form should be Community based, not All Farcaster.
![image](https://github.com/vocdoni/vote-frame/assets/3515290/d25b9c45-1650-4e2b-adc0-dbb51c5fcdb7)

**Comment by elboletaire** [comment]
Closing this after having created issues for the three missing things.
